### ISSUE TITLE
Nill pointer error when including styles

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/curation_concerns#217]
In my application.scss I'm doing:
```
 @import 'curation_concerns/curation_concerns';
```

This causes:
```
undefined method `start_with?' for nil:NilClass

Extracted source (around line #111):

109
110
111
112
113
114
              

	

      return "" if path == subpath
      path = File.join(path, '')
      if subpath.start_with?(path)
        subpath[path.length..-1]
      else
        nil

Trace of template inclusion: /Users/justin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/curation_concerns-9b49d4d66ed5/app/views/layouts/curation_concerns.html.erb, /Users/justin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/curation_concerns-9b49d4d66ed5/app/views/layouts/curation_concerns/1_column.html.erb

Rails.root: /Users/justin/workspace/goldenseal
Application Trace | Framework Trace | Full Trace

sprockets (3.3.3) lib/sprockets/path_utils.rb:111:in `split_subpath'
sprockets (3.3.3) lib/sprockets/path_utils.rb:126:in `block in paths_split'
sprockets (3.3.3) lib/sprockets/path_utils.rb:125:in `each'
sprockets (3.3.3) lib/sprockets/path_utils.rb:125:in `paths_split'
sprockets (3.3.3) lib/sprockets/resolve.rb:95:in `resolve_relative_path'
sprockets (3.3.3) lib/sprockets/resolve.rb:33:in `resolve'
sprockets (3.3.3) lib/sprockets/legacy.rb:66:in `resolve_with_compat'
sprockets (3.3.3) lib/sprockets/base.rb:64:in `find_asset'
sprockets (3.3.3) lib/sprockets/base.rb:92:in `[]'
sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:230:in `lookup_asset_for_path'
sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:190:in `check_errors_for'
sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:89:in `asset_path'
sprockets (3.3.3) lib/sprockets/sass_processor.rb:112:in `asset_path'
sprockets (3.3.3) lib/sprockets/sass_processor.rb:188:in `font_path'
sass (3.4.18) lib/sass/script/tree/funcall.rb:140:in `_perform'
sass (3.4.18) lib/sass/script/tree/node.rb:50:in `perform'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:403:in `visit_return'
sass (3.4.18) lib/sass/tree/visitors/base.rb:36:in `visit'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
sass (3.4.18) lib/sass/stack.rb:79:in `block in with_base'
sass (3.4.18) lib/sass/stack.rb:115:in `with_frame'
sass (3.4.18) lib/sass/stack.rb:79:in `with_base'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:158:in `visit'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:8:in `visit'
sass (3.4.18) lib/sass/script/tree/funcall.rb:248:in `block (3 levels) in perform_sass_fn'
sass (3.4.18) lib/sass/script/tree/funcall.rb:248:in `each'
sass (3.4.18) lib/sass/script/tree/funcall.rb:248:in `block (2 levels) in perform_sass_fn'
sass (3.4.18) lib/sass/script/tree/funcall.rb:247:in `catch'
sass (3.4.18) lib/sass/script/tree/funcall.rb:247:in `block in perform_sass_fn'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:84:in `perform_arguments'
sass (3.4.18) lib/sass/script/tree/funcall.rb:244:in `perform_sass_fn'
sass (3.4.18) lib/sass/script/tree/funcall.rb:131:in `_perform'
sass (3.4.18) lib/sass/script/tree/node.rb:50:in `perform'
sass (3.4.18) lib/sass/script/functions.rb:593:in `perform'
sass (3.4.18) lib/sass/script/functions.rb:2188:in `if'
sass (3.4.18) lib/sass/script/tree/funcall.rb:140:in `_perform'
sass (3.4.18) lib/sass/script/tree/node.rb:50:in `perform'
sass (3.4.18) lib/sass/script/tree/funcall.rb:170:in `perform_arg'
sass (3.4.18) lib/sass/script/tree/funcall.rb:124:in `block in _perform'
sass (3.4.18) lib/sass/script/tree/funcall.rb:124:in `each'
sass (3.4.18) lib/sass/script/tree/funcall.rb:124:in `each_with_index'
sass (3.4.18) lib/sass/script/tree/funcall.rb:124:in `each'
sass (3.4.18) lib/sass/script/tree/funcall.rb:124:in `map'
sass (3.4.18) lib/sass/script/tree/funcall.rb:124:in `_perform'
sass (3.4.18) lib/sass/script/tree/node.rb:50:in `perform'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:395:in `visit_prop'
sass (3.4.18) lib/sass/tree/visitors/base.rb:36:in `visit'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
sass (3.4.18) lib/sass/stack.rb:79:in `block in with_base'
sass (3.4.18) lib/sass/stack.rb:115:in `with_frame'
sass (3.4.18) lib/sass/stack.rb:79:in `with_base'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:158:in `visit'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:502:in `block (2 levels) in visit_directive'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:502:in `map'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:502:in `block in visit_directive'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:179:in `with_environment'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:501:in `visit_directive'
sass (3.4.18) lib/sass/tree/visitors/base.rb:36:in `visit'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
sass (3.4.18) lib/sass/stack.rb:79:in `block in with_base'
sass (3.4.18) lib/sass/stack.rb:115:in `with_frame'
sass (3.4.18) lib/sass/stack.rb:79:in `with_base'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:158:in `visit'
sass (3.4.18) lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
sass (3.4.18) lib/sass/tree/visitors/base.rb:52:in `map'
sass (3.4.18) lib/sass/tree/visitors/base.rb:52:in `visit_children'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:179:in `with_environment'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:166:in `visit_children'
sass (3.4.18) lib/sass/tree/visitors/base.rb:36:in `block in visit'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:454:in `visit_atroot'
sass (3.4.18) lib/sass/tree/visitors/base.rb:36:in `visit'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
sass (3.4.18) lib/sass/stack.rb:79:in `block in with_base'
sass (3.4.18) lib/sass/stack.rb:115:in `with_frame'
sass (3.4.18) lib/sass/stack.rb:79:in `with_base'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:158:in `visit'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:326:in `block (2 levels) in visit_import'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:326:in `map'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:326:in `block in visit_import'
sass (3.4.18) lib/sass/stack.rb:88:in `block in with_import'
sass (3.4.18) lib/sass/stack.rb:115:in `with_frame'
sass (3.4.18) lib/sass/stack.rb:88:in `with_import'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:323:in `visit_import'
sass (3.4.18) lib/sass/tree/visitors/base.rb:36:in `visit'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
sass (3.4.18) lib/sass/stack.rb:79:in `block in with_base'
sass (3.4.18) lib/sass/stack.rb:115:in `with_frame'
sass (3.4.18) lib/sass/stack.rb:79:in `with_base'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:158:in `visit'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:326:in `block (2 levels) in visit_import'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:326:in `map'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:326:in `block in visit_import'
sass (3.4.18) lib/sass/stack.rb:88:in `block in with_import'
sass (3.4.18) lib/sass/stack.rb:115:in `with_frame'
sass (3.4.18) lib/sass/stack.rb:88:in `with_import'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:323:in `visit_import'
sass (3.4.18) lib/sass/tree/visitors/base.rb:36:in `visit'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
sass (3.4.18) lib/sass/stack.rb:79:in `block in with_base'
sass (3.4.18) lib/sass/stack.rb:115:in `with_frame'
sass (3.4.18) lib/sass/stack.rb:79:in `with_base'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:158:in `visit'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:326:in `block (2 levels) in visit_import'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:326:in `map'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:326:in `block in visit_import'
sass (3.4.18) lib/sass/stack.rb:88:in `block in with_import'
sass (3.4.18) lib/sass/stack.rb:115:in `with_frame'
sass (3.4.18) lib/sass/stack.rb:88:in `with_import'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:323:in `visit_import'
sass (3.4.18) lib/sass/tree/visitors/base.rb:36:in `visit'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
sass (3.4.18) lib/sass/stack.rb:79:in `block in with_base'
sass (3.4.18) lib/sass/stack.rb:115:in `with_frame'
sass (3.4.18) lib/sass/stack.rb:79:in `with_base'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:158:in `visit'
sass (3.4.18) lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
sass (3.4.18) lib/sass/tree/visitors/base.rb:52:in `map'
sass (3.4.18) lib/sass/tree/visitors/base.rb:52:in `visit_children'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:179:in `with_environment'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:166:in `visit_children'
sass (3.4.18) lib/sass/tree/visitors/base.rb:36:in `block in visit'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:186:in `visit_root'
sass (3.4.18) lib/sass/tree/visitors/base.rb:36:in `visit'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:157:in `visit'
sass (3.4.18) lib/sass/tree/visitors/perform.rb:8:in `visit'
sass (3.4.18) lib/sass/tree/root_node.rb:36:in `css_tree'
sass (3.4.18) lib/sass/tree/root_node.rb:20:in `render'
sass (3.4.18) lib/sass/engine.rb:278:in `render'
sass-rails (5.0.3) lib/sass/rails/template.rb:47:in `evaluate'
tilt (1.4.1) lib/tilt/template.rb:103:in `render'
sprockets (3.3.3) lib/sprockets/legacy_tilt_processor.rb:25:in `call'
sprockets (3.3.3) lib/sprockets/processor_utils.rb:75:in `call_processor'
sprockets (3.3.3) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
sprockets (3.3.3) lib/sprockets/processor_utils.rb:56:in `reverse_each'
sprockets (3.3.3) lib/sprockets/processor_utils.rb:56:in `call_processors'
sprockets (3.3.3) lib/sprockets/loader.rb:134:in `load_from_unloaded'
sprockets (3.3.3) lib/sprockets/loader.rb:60:in `block in load'
sprockets (3.3.3) lib/sprockets/loader.rb:316:in `fetch_asset_from_dependency_cache'
sprockets (3.3.3) lib/sprockets/loader.rb:44:in `load'
sprockets (3.3.3) lib/sprockets/cached_environment.rb:20:in `block in initialize'
sprockets (3.3.3) lib/sprockets/cached_environment.rb:47:in `yield'
sprockets (3.3.3) lib/sprockets/cached_environment.rb:47:in `load'
sprockets (3.3.3) lib/sprockets/bundle.rb:23:in `block in call'
sprockets (3.3.3) lib/sprockets/utils.rb:183:in `dfs'
sprockets (3.3.3) lib/sprockets/bundle.rb:24:in `call'
sprockets (3.3.3) lib/sprockets/processor_utils.rb:75:in `call_processor'
sprockets (3.3.3) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
sprockets (3.3.3) lib/sprockets/processor_utils.rb:56:in `reverse_each'
sprockets (3.3.3) lib/sprockets/processor_utils.rb:56:in `call_processors'
sprockets (3.3.3) lib/sprockets/loader.rb:134:in `load_from_unloaded'
sprockets (3.3.3) lib/sprockets/loader.rb:60:in `block in load'
sprockets (3.3.3) lib/sprockets/loader.rb:316:in `fetch_asset_from_dependency_cache'
sprockets (3.3.3) lib/sprockets/loader.rb:44:in `load'
sprockets (3.3.3) lib/sprockets/cached_environment.rb:20:in `block in initialize'
sprockets (3.3.3) lib/sprockets/cached_environment.rb:47:in `yield'
sprockets (3.3.3) lib/sprockets/cached_environment.rb:47:in `load'
sprockets (3.3.3) lib/sprockets/base.rb:66:in `find_asset'
sprockets (3.3.3) lib/sprockets/environment.rb:30:in `find_asset'
sprockets (3.3.3) lib/sprockets/base.rb:92:in `[]'
sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:230:in `lookup_asset_for_path'
sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:190:in `check_errors_for'
sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:159:in `block in stylesheet_link_tag'
sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:158:in `map'
sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:158:in `stylesheet_link_tag'
/Users/justin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/curation_concerns-9b49d4d66ed5/app/views/layouts/boilerplate.html.erb:12:in 
```

**Comment by jcoyne** [comment]
This was caused by
```
@import 'bootstrap';
@import 'blacklight/blacklight';
```

being in the application.scss file.  After removing them all is fine.
