### ISSUE TITLE
Can't set lease or embargo on initial ingest

### ISSUE THREAD

**Issue by terrellt** [projecthydra-labs/curation_concerns#253]
```
Invalid visibility: "lease"

hydra-access-controls (9.2.2) app/models/concerns/hydra/access_controls/visibility.rb:17:in `visibility='
hydra-access-controls (9.2.2) app/models/concerns/hydra/access_controls/embargoable.rb:58:in `visibility='
/Users/tterrell/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/curation_concerns-94d7c7d3580a/curation_concerns-models/app/actors/curation_concerns/work_actor_behavior.rb:72:in `attach_file'
/Users/tterrell/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/curation_concerns-94d7c7d3580a/curation_concerns-models/app/actors/curation_concerns/work_actor_behavior.rb:32:in `block in attach_files'
/Users/tterrell/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/curation_concerns-94d7c7d3580a/curation_concerns-models/app/actors/curation_concerns/work_actor_behavior.rb:31:in `each'
/Users/tterrell/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/curation_concerns-94d7c7d3580a/curation_concerns-models/app/actors/curation_concerns/work_actor_behavior.rb:31:in `all?'
/Users/tterrell/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/curation_concerns-94d7c7d3580a/curation_concerns-models/app/actors/curation_concerns/work_actor_behavior.rb:31:in `attach_files'
/Users/tterrell/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/curation_concerns-94d7c7d3580a/curation_concerns-models/app/actors/curation_concerns/work_actor_behavior.rb:8:in `create'
/Users/tterrell/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/curation_concerns-94d7c7d3580a/app/controllers/concerns/curation_concerns/curation_concern_controller.rb:35:in `create'
```

**Comment by terrellt** [comment]
@jcoyne Did you run into this spinning up a CC app?

**Comment by jcoyne** [comment]
Yes. I see that too.

**Comment by jcoyne** [comment]
I think worthwhile had something in it's actors that stripped out the lease or embargo visibility from the params.  This could be missing.

**Comment by jcoyne** [comment]
Probably this: https://github.com/projecthydra-labs/worthwhile/blob/master/worthwhile-models/app/actors/concerns/worthwhile/manages_embargoes_actor.rb#L43
