### ISSUE TITLE
Create GenericFile ("attach a file") with lease visibility raises an error

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/curation_concerns#310]
```
F, [2015-09-09T15:27:37.070880 #32667] FATAL -- :
ArgumentError (Invalid visibility: "lease"):
  hydra-access-controls (9.2.2) app/models/concerns/hydra/access_controls/visibility.rb:17:in `visibility='
  hydra-access-controls (9.2.2) app/models/concerns/hydra/access_controls/embargoable.rb:58:in `visibility='
  active-fedora (9.3.0) lib/active_fedora/attributes.rb:24:in `block in attributes='
  actionpack (4.2.4) lib/action_controller/metal/strong_parameters.rb:185:in `each_pair'
  actionpack (4.2.4) lib/action_controller/metal/strong_parameters.rb:185:in `each_pair'
  active-fedora (9.3.0) lib/active_fedora/attributes.rb:23:in `attributes='
  active-fedora (9.3.0) lib/active_fedora/attributes/serializers.rb:26:in `attributes='
  active-fedora (9.3.0) lib/active_fedora/core.rb:34:in `initialize'
  cancancan (1.12.0) lib/cancan/controller_resource.rb:80:in `new'
  cancancan (1.12.0) lib/cancan/controller_resource.rb:80:in `build_resource'
  cancancan (1.12.0) lib/cancan/controller_resource.rb:61:in `load_resource_instance'
  cancancan (1.12.0) lib/cancan/controller_resource.rb:32:in `load_resource'
  cancancan (1.12.0) lib/cancan/controller_resource.rb:25:in `load_and_authorize_resource'
  cancancan (1.12.0) lib/cancan/controller_resource.rb:10:in `block in add_before_filter'
  activesupport (4.2.4) lib/active_support/callbacks.rb:448:in `instance_exec'
  activesupport (4.2.4) lib/active_support/callbacks.rb:448:in `block in make_lambda'
  activesupport (4.2.4) lib/active_support/callbacks.rb:145:in `call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:145:in `block in halting_and_conditional'
  activesupport (4.2.4) lib/active_support/callbacks.rb:504:in `call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:504:in `block in call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:504:in `each'
  activesupport (4.2.4) lib/active_support/callbacks.rb:504:in `call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.4) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.4) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.4) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.4) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.4) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.4) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.4) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.4) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.4) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.4) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.4) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.4) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:76:in `call'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:45:in `serve'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:821:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
```

**Comment by blancoj** [comment]
Gordon and I are working on this one.  10/21/2015

**Comment by jcoyne** [comment]
The problem here is that cancan is assigining the parameters, it should not be allowed to do this with "visibility".  I believe this issue is already closed, unless you've been able to duplicate @blancoj ?

**Comment by blancoj** [comment]
I was able to duplicate it in my instance of curation concerns.  When I loaded a file and set it to lease, I got the same error.

**Comment by jcoyne** [comment]
blancoj: Were you able to duplicate it using the UI or only via the command line?

**Comment by jcoyne** [comment]
`Invalid visibility: "lease"` is a reasonable error if you do `file_set.visibility = 'lease'`, because it is not valid. However there should be no way to surface this error via the GUI.  https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/actors/concerns/curation_concerns/manages_embargoes_actor.rb#L25 should be handling it for you.

**Comment by blancoj** [comment]
I duplicated the error using the release version of curation concerns.  I'll test it out with the current code base and see what happens.

**Comment by blancoj** [comment]
The released version in the UI is what I meant.

**Comment by blancoj** [comment]
I just tried using the UI from the master code and I can't attach a file to a work without getting an error.  I get different types of errors depending on the right I assign to the file.  It could be my environment - could some one else test it?

**Comment by jcoyne** [comment]
I am unable to get that error. Can you write a test that shows the problem?

**Comment by blancoj** [comment]
Can you test it using the UI?  That's what I did.  I tried to create a new work and then uploaded a file and set it's right to lease.

**Comment by jcoyne** [comment]
Yes, I've tested using the UI, added a file and set it's right to lease. No problems:

**Comment by blancoj** [comment]
OK, so it must be something in my environment.  Thanks for testing it.

-Jose
