### ISSUE TITLE
Deleting a GenericFile from a Work breaks the work show page

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/curation_concerns#326]
```
I, [2015-09-11T05:10:22.679526 #2902]  INFO -- : Completed 500 Internal Server Error in 34ms (ActiveRecord: 0.2ms)
F, [2015-09-11T05:10:22.682015 #2902] FATAL -- :
ActionView::Template::Error (undefined method `fetch' for nil:NilClass):
    14:       </tr>
    15:     </thead>
    16:     <tbody>
    17:       <%= render presenter.file_presenters %>
    18:     </tbody>
    19:   </table>
    20: </div>
  /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-d6acb032f6e0/app/presenters/curation_concerns/model_proxy.rb:24:in `_delegated_to'
  /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-d6acb032f6e0/app/presenters/curation_concerns/model_proxy.rb:10:in `to_partial_path'
  actionview (4.2.4) lib/action_view/renderer/partial_renderer.rb:476:in `partial_path'
  actionview (4.2.4) lib/action_view/renderer/partial_renderer.rb:379:in `block in setup'
  actionview (4.2.4) lib/action_view/renderer/partial_renderer.rb:379:in `map'
  actionview (4.2.4) lib/action_view/renderer/partial_renderer.rb:379:in `setup'
  actionview (4.2.4) lib/action_view/renderer/partial_renderer.rb:293:in `render'
  actionview (4.2.4) lib/action_view/renderer/renderer.rb:47:in `render_partial'
  actionview (4.2.4) lib/action_view/helpers/rendering_helper.rb:35:in `render'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:12:in `render_with_haml'
  /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-d6acb032f6e0/app/views/curation_concerns/base/_related_files.html.erb:17:in `__opt_goldenseal_shared_bundle_ruby_______bundler_gems_curation_concerns_d_acb___f_e__app_views_curation_concerns_base__related_files_html_erb___2537971305120820614_83541640'
  actionview (4.2.4) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.4) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.4) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.4) lib/action_view/template.rb:143:in `render'
  actionview (4.2.4) lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
  actionview (4.2.4) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
  actionview (4.2.4) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.4) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.4) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.4) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.4) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.4) lib/action_view/renderer/partial_renderer.rb:309:in `render'
  actionview (4.2.4) lib/action_view/renderer/renderer.rb:47:in `render_partial'
  actionview (4.2.4) lib/action_view/helpers/rendering_helper.rb:35:in `render'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:12:in `render_with_haml'
  /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-d6acb032f6e0/app/views/curation_concerns/base/show.html.erb:11:in `__opt_goldenseal_shared_bundle_ruby_______bundler_gems_curation_concerns_d_acb___f_e__app_views_curation_concerns_base_show_html_erb___2423873013862554650_88016080'
```

**Comment by jcoyne** [comment]
This is because the parent work has a list of identifier some of which no longer exist:

```ruby
ids = ActiveFedora::SolrService.query('id:6q182k142').first.fetch('generic_file_ids_ssim')
=> ["w95050457", "2801pg32c", "pz50gw11f", "5h73pw05j", "2n49t1681"]
ids.map { |child| ActiveFedora::SolrService.query("id:#{child}").present? }
=> [true, true, true, false, true]
```
