### ISSUE TITLE
Including just ::CurationConcerns::WorkBehavior is insufficent

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/curation_concerns#433]
```ruby
class Foo < ActiveFedora::Base
  include ::CurationConcerns::WorkBehavior
end

i = Foo.create()

/Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activemodel-4.2.4/lib/active_model/attribute_methods.rb:433:in `method_missing': undefined method `depositor' for #<Foo:0x007faeb7951b00> (NoMethodError)
	from /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/curation_concerns-models-0.2.0/app/models/concerns/curation_concerns/permissions/writable.rb:27:in `block in paranoid_edit_permissions'
	from /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/curation_concerns-models-0.2.0/app/models/concerns/curation_concerns/permissions/writable.rb:17:in `call'
	from /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/curation_concerns-models-0.2.0/app/models/concerns/curation_concerns/permissions/writable.rb:17:in `block in paranoid_permissions'
	from /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/curation_concerns-models-0.2.0/app/models/concerns/curation_concerns/permissions/writable.rb:16:in `each'
	from /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/curation_concerns-models-0.2.0/app/models/concerns/curation_concerns/permissions/writable.rb:16:in `paranoid_permissions'
	from /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:432:in `block in make_lambda'
	from /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:192:in `call'
	from /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:192:in `block in simple'
	from /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:504:in `call'
	from /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:504:in `block in call'
	from /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:504:in `each'
	from /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:504:in `call'
	from /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
	from /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_validate_callbacks'
	from /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activemodel-4.2.4/lib/active_model/validations.rb:398:in `run_validations!'
	from /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activemodel-4.2.4/lib/active_model/validations.rb:337:in `valid?'
	from /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/active-fedora-9.5.0/lib/active_fedora/validations.rb:69:in `valid?'
	from /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/active-fedora-9.5.0/lib/active_fedora/validations.rb:84:in `perform_validations'
	from /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/active-fedora-9.5.0/lib/active_fedora/validations.rb:50:in `save'
	from /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/active-fedora-9.5.0/lib/active_fedora/persistence.rb:107:in `create'
```

**Comment by awead** [comment]
`include CurationConcerns::BasicMetadata` ? Based on the test:
https://github.com/projecthydra-labs/curation_concerns/blob/master/spec/models/curation_concerns/work_behavior_spec.rb#L7
