### ISSUE TITLE
undefined method CurationConcerns::CharacterizationService.run

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/curation_concerns#82]
I'm getting this error
```
     NoMethodError:
       undefined method `run' for CurationConcerns::CharacterizationService:Class
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/curation_concerns-44d7e828b336/curation_concerns-models/app/jobs/characterize_job.rb:7:in `run'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/curation_concerns-44d7e828b336/curation_concerns-models/lib/curation_concerns/models/resque.rb:32:in `perform'
```

which seems odd considering it does seem to be defined: https://github.com/projecthydra-labs/curation_concerns/blob/44d7e828b336526ab8edef90c70babe138ce6b58/curation_concerns-models/app/services/curation_concerns/characterization_service.rb#L10

**Comment by jcoyne** [comment]
Mocking error. Mea culpa.
